import { getExtension } from "./diff.ts";

/** Comment style definitions per language family. */
interface CommentStyle {
  single: string[];
  blockStart?: string;
  blockEnd?: string;
}

const STYLES: Record<string, CommentStyle> = {
  clike: { single: ["//"], blockStart: "/*", blockEnd: "*/" },
  hash: { single: ["#"] },
  html: { single: [], blockStart: "<!--", blockEnd: "-->" },
  lua: { single: ["--"], blockStart: "--[[", blockEnd: "]]" },
  sql: { single: ["--"], blockStart: "/*", blockEnd: "*/" },
  lisp: { single: [";"] },
  latex: { single: ["%"] },
  python: { single: ["#"], blockStart: '"""', blockEnd: '"""' },
  ruby: { single: ["#"], blockStart: "=begin", blockEnd: "=end" },
};

const EXT_TO_STYLE: Record<string, CommentStyle> = {};

function register(exts: string[], style: CommentStyle) {
  for (const ext of exts) EXT_TO_STYLE[ext] = style;
}

register(
  ["ts", "tsx", "js", "jsx", "mjs", "cjs", "java", "kt", "kts",
   "c", "h", "cpp", "cc", "cxx", "hpp", "cs", "go", "rs", "swift",
   "scala", "dart", "m", "mm", "zig", "v", "groovy", "gradle"],
  STYLES.clike,
);
register(["py", "pyi"], STYLES.python);
register(["rb", "rake", "gemspec"], STYLES.ruby);
register(
  ["sh", "bash", "zsh", "fish", "yml", "yaml", "toml", "ini", "conf",
   "dockerfile", "makefile", "cmake", "r", "pl", "pm", "t", "ex", "exs",
   "elixir", "nim", "cr", "jl"],
  STYLES.hash,
);
register(["html", "htm", "xml", "svg", "vue", "svelte", "md"], STYLES.html);
register(["lua"], STYLES.lua);
register(["sql", "psql", "plsql"], STYLES.sql);
register(["el", "lisp", "cl", "clj", "cljs", "scm", "rkt"], STYLES.lisp);
register(["tex", "sty", "cls", "bib", "erl", "hrl", "matlab", "m"], STYLES.latex);
register(["css", "scss", "sass", "less"], STYLES.clike);

/** Patterns for trivial/generated comments to ignore. */
const TRIVIAL_PATTERNS = [
  /^\s*eslint-disable/i,
  /^\s*@ts-(?:ignore|expect-error|nocheck)/i,
  /^\s*noinspection\b/i,
  /^\s*pragma\b/i,
  /^\s*istanbul\s+ignore/i,
  /^\s*c8\s+ignore/i,
  /^\s*type:\s*ignore/i,
  /^\s*noqa\b/i,
  /^\s*rubocop:/i,
  /^\s*(?:auto-generated|generated by|do not edit)/i,
  /^\s*TODO\(bot\)/i,
  /^\s*prettier-ignore/i,
  /^\s*vim:/i,
  /^\s*-\*-\s*\w+/i,
];

function isTrivial(text: string): boolean {
  return TRIVIAL_PATTERNS.some((p) => p.test(text));
}

/** Block comment tracking state. */
interface BlockState {
  active: boolean;
  endMarker: string;
}

/**
 * Extract comment text from a single line of code.
 * Returns the comment body (stripped of delimiters) or null if no comment found.
 */
export function extractComment(
  line: string,
  filePath: string,
  block: BlockState = { active: false, endMarker: "" },
): { comment: string | null; block: BlockState } {
  const ext = getExtension(filePath);
  const style = EXT_TO_STYLE[ext];

  if (!style) {
    return { comment: null, block };
  }

  const trimmed = line.trimStart();

  // Currently inside a block comment
  if (block.active) {
    const endIdx = trimmed.indexOf(block.endMarker);
    if (endIdx !== -1) {
      const text = trimmed.slice(0, endIdx).replace(/^\*\s?/, "").trim();
      return {
        comment: text || null,
        block: { active: false, endMarker: "" },
      };
    }
    // Continuation line inside block — strip leading * if present
    const text = trimmed.replace(/^\*\s?/, "").trim();
    return {
      comment: text || null,
      block,
    };
  }

  // Check block comment start
  if (style.blockStart && style.blockEnd) {
    const bsIdx = trimmed.indexOf(style.blockStart);
    if (bsIdx !== -1 && (style.single.length === 0 || bsIdx <= firstSingleIdx(trimmed, style.single))) {
      const afterStart = trimmed.slice(bsIdx + style.blockStart.length);
      const endIdx = afterStart.indexOf(style.blockEnd);
      if (endIdx !== -1) {
        // Single-line block comment: /* text */
        const text = afterStart.slice(0, endIdx).trim();
        return {
          comment: text || null,
          block: { active: false, endMarker: "" },
        };
      }
      // Block opens but doesn't close on this line
      const text = afterStart.replace(/^\*?\s?/, "").trim();
      return {
        comment: text || null,
        block: { active: true, endMarker: style.blockEnd },
      };
    }
  }

  // Check single-line comments
  for (const marker of style.single) {
    const idx = trimmed.indexOf(marker);
    if (idx !== -1) {
      // Simple heuristic: if the marker appears at the start or after whitespace/code
      // For '#' in particular, skip shebang lines
      if (marker === "#" && trimmed.startsWith("#!")) continue;
      const text = trimmed.slice(idx + marker.length).trim();
      return { comment: text || null, block };
    }
  }

  return { comment: null, block };
}

function firstSingleIdx(line: string, markers: string[]): number {
  let min = Infinity;
  for (const m of markers) {
    const idx = line.indexOf(m);
    if (idx !== -1 && idx < min) min = idx;
  }
  return min;
}

/**
 * Extract all comments from a list of added lines for a single file.
 * Returns array of { lineNumber, comment } objects.
 */
export function extractCommentsFromLines(
  lines: { lineNumber: number; content: string }[],
  filePath: string,
): { lineNumber: number; comment: string }[] {
  const results: { lineNumber: number; comment: string }[] = [];
  let block: BlockState = { active: false, endMarker: "" };

  for (const { lineNumber, content } of lines) {
    const { comment, block: newBlock } = extractComment(content, filePath, block);
    block = newBlock;
    if (comment && !isTrivial(comment)) {
      results.push({ lineNumber, comment });
    }
  }

  return results;
}
